### PR TITLE
Enhancements.

### PR DESCRIPTION
**Pull request by ypid**

### CODE REVIEW

**Comment by TalLannder** [comment]
Sorry but I can't see a valid reason for the complexity you introduced with additional variables just define the existing "mount" variable in host_vars or group_vars. The README file is also doesn't fully document the changes you made in addition this change will break any existing users which is not desired.

This part is pretty awesome, although once again why with_flattened and not one variable? 

```
+- name: Debian | Ensure required packages are installed
+  apt:
+    name: '{{ mount_packages["Debian"][item.fstype] }}'
+    state: 'latest'
+  when: (item.fstype is string and item.fstype in ['cifs', 'nfs'])
+  with_flattened:
+    - mount_list
+    - mount_group_list
+    - mount_host_list
```

**Comment by ypid** [comment]
Fair enough and thanks for the complement :smile: I also like this part. For the
three variables checkout the http://debops.org/ project. They do this as there
best practice and I agree with it. The reason for this is quite simple. I for
example use it to define some mountpoints (like tmpfs for /tmp) on a site-level
and then optionally define mountpoints (smb and so on) on an host or group
level. Maybe we can introduce another variable called `mount` to don’t break
backwards comparability?

**Comment by TalLannder** [comment]
Well that make since for some use cases but in general I'm trying to keep any environment as clusters and define all the variables on a cluster basis (in group_vars) even if it's one node (KEEP IT SIMPLE :). This way it's really clean and when new people coming on board they don't need years of experience to get up to speed and deal with variables inheritance that previous folks implemented. But feel free if you see the need just introduce new variables to support you're use case say mountGlobal, mountGroup and leave the existing one for backwards comp..

**Comment by ypid** [comment]
`mountGlobal` as variable is not best-practice. I updated my PR.

Define all hosts as clusters is not always possible. I am mainly using Ansible to manage my systems at home :smile:

**Comment by TalLannder** [comment]
Thanks for the update, did you update the README? to reflect new functionality?

**Comment by ypid** [comment]
I think READMEs for ansible roles should be generated automatically. What do you think about using [ansigenome](https://github.com/nickjj/ansigenome) for this?

**Comment by TalLannder** [comment]
Sorry men but I don't have the capacity for it right now.

**Comment by ypid** [comment]
Turns out [debops.console](https://github.com/debops/ansible-console) also handles mounts … So I am using debops.console. You might want to cherry-pick some commits from this PR if you want or just remove the additional variables.

**Comment by TalLannder** [comment]
@ypid Thanks a lot for the contribution! unfortunately this pull request still brakes backward compatibility and lacking the docs as I mentioned before. I'll close it for now since it seems that we don't have the time to polish this code.

**Pull request closed without merging**
